# Generated by Django 3.0.8 on 2020-08-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=40, null=True)),
                ('designation', models.CharField(max_length=40, null=True)),
                ('average_height', models.CharField(max_length=40, null=True)),
                ('skin_colors', models.CharField(max_length=200, null=True)),
                ('hair_colors', models.CharField(max_length=200, null=True)),
                ('eye_colors', models.CharField(max_length=200, null=True)),
                ('average_lifespan', models.CharField(max_length=40, null=True)),
                ('language', models.CharField(max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
                'db_table': 'species',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
