# Generated by Django 3.0.8 on 2020-08-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('planet_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('rotation_period', models.CharField(max_length=40, null=True)),
                ('orbital_period', models.CharField(max_length=40, null=True)),
                ('diameter', models.CharField(max_length=40, null=True)),
                ('climate', models.CharField(max_length=40, null=True)),
                ('gravity', models.CharField(max_length=40, null=True)),
                ('terrain', models.CharField(max_length=40, null=True)),
                ('surface_water', models.CharField(max_length=40, null=True)),
                ('population', models.CharField(max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Planet',
                'verbose_name_plural': 'Planets',
                'db_table': 'planet',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
