# Generated by Django 3.0.8 on 2020-08-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200806_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='home_world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_home_world', to='webapp.Planet'),
        ),
        migrations.AddField(
            model_name='person',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='species', to='webapp.Species'),
        ),
        migrations.AddField(
            model_name='species',
            name='home_world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='species_home_world', to='webapp.Planet'),
        ),
    ]
