# Generated by Django 3.1.2 on 2020-10-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_starship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Starship',
            new_name='Starships',
        ),
        migrations.AlterModelOptions(
            name='starships',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Starships', 'verbose_name_plural': 'Starships'},
        ),
    ]
