# Generated by Django 3.1.2 on 2020-10-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='home_world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='film_home_world', to='webapp.planet'),
        ),
        migrations.AddField(
            model_name='film',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='film_species', to='webapp.species'),
        ),
        migrations.AlterField(
            model_name='person',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_species', to='webapp.species'),
        ),
    ]
