# Generated by Django 3.1.2 on 2020-10-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20201002_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='home_world',
        ),
        migrations.AddField(
            model_name='film',
            name='planets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='film_planets', to='webapp.planet'),
        ),
        migrations.AlterField(
            model_name='film',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='film_people', to='webapp.person'),
        ),
    ]
