# Generated by Django 3.1 on 2020-10-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_person_owner'),
        ('webapp', '0008_auto_20201009_1152'),
    ]

    operations = [
    ]
