# Generated by Django 3.1 on 2020-10-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_merge_20201023_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='owner',
        ),
    ]
