# Generated by Django 3.1 on 2020-10-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20201007_1725'),
        ('webapp', '0010_remove_person_owner'),
    ]

    operations = [
    ]
