# Generated by Django 3.1 on 2020-10-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_merge_20201023_1257'),
        ('webapp', '0006_vehicles'),
    ]

    operations = [
    ]
