# Generated by Django 3.1 on 2020-11-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_merge_20201027_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='people',
            new_name='characters',
        ),
    ]
