# Generated by Django 3.1.2 on 2020-11-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_merge_20201027_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Starships',
            new_name='Starship',
        ),
        migrations.AlterModelOptions(
            name='starship',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Starship', 'verbose_name_plural': 'Starships'},
        ),
        migrations.AlterModelTable(
            name='starship',
            table='starship',
        ),
    ]
