# Generated by Django 3.1 on 2020-11-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20201120_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='characters',
        ),
        migrations.AddField(
            model_name='film',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='film_people', to='webapp.Person'),
        ),
        migrations.RemoveField(
            model_name='film',
            name='planets',
        ),
        migrations.AddField(
            model_name='film',
            name='planets',
            field=models.ManyToManyField(blank=True, related_name='film_planets', to='webapp.Planet'),
        ),
        migrations.RemoveField(
            model_name='film',
            name='species',
        ),
        migrations.AddField(
            model_name='film',
            name='species',
            field=models.ManyToManyField(blank=True, related_name='film_species', to='webapp.Species'),
        ),
    ]
