# Generated by Django 3.1 on 2020-11-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20201113_0702'),
        ('webapp', '0014_auto_20201120_1318'),
    ]

    operations = [
    ]
