# Generated by Django 3.1 on 2020-11-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_merge_20201120_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='starships',
            field=models.ManyToManyField(blank=True, related_name='film_starships', to='webapp.Starship'),
        ),
    ]
