# Generated by Django 3.1.2 on 2021-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_film_starships'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmPerson',
            fields=[
                ('film_person_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Film Character',
                'verbose_name_plural': 'Film Characters',
                'db_table': 'film_person',
                'ordering': ['film', 'person'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmPlanet',
            fields=[
                ('film_planet_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Film Planet',
                'verbose_name_plural': 'Film Planets',
                'db_table': 'film_planet',
                'ordering': ['film', 'planet'],
                'managed': False,
            },
        ),
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'managed': False, 'ordering': ['title'], 'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='planet',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Planet', 'verbose_name_plural': 'Planets'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='starship',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Starship', 'verbose_name_plural': 'Starships'},
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicles_id',
            new_name='vehicle_id',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
    ]
