# Generated by Django 3.1.7 on 2021-03-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20210218_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePerson',
            fields=[
                ('vehicle_person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.person')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Person',
                'verbose_name_plural': 'Vehicle Persons',
                'db_table': 'vehicle_person',
                'ordering': ['vehicle', 'person'],
                'managed': True,
                'unique_together': {('vehicle', 'person')},
            },
        ),
    ]
