# Generated by Django 3.1.7 on 2021-03-19 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20210318_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmJurisdiction',
            fields=[
                ('film_jurisdiction_id', models.AutoField(primary_key=True, serialize=False)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.film')),
            ],
            options={
                'verbose_name': 'Film Jurisdiction',
                'verbose_name_plural': 'Film Jurisdictions',
                'db_table': 'film_jurisdiction',
                'ordering': ['film'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FilmPerson',
            fields=[
                ('film_person_id', models.AutoField(primary_key=True, serialize=False)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.film')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.person')),
            ],
            options={
                'verbose_name': 'Film Character',
                'verbose_name_plural': 'Film Characters',
                'db_table': 'film_person',
                'ordering': ['film', 'person'],
                'managed': True,
                'unique_together': {('film', 'person')},
            },
        ),
        migrations.CreateModel(
            name='FilmPlanet',
            fields=[
                ('film_planet_id', models.AutoField(primary_key=True, serialize=False)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.film')),
                ('planet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.planet')),
            ],
            options={
                'verbose_name': 'Film Planet',
                'verbose_name_plural': 'Film Planets',
                'db_table': 'film_planet',
                'ordering': ['film', 'planet'],
                'managed': True,
                'unique_together': {('film', 'planet')},
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pilots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_person', to='webapp.person'),
        ),
    ]
