# Generated by Django 3.1.7 on 2021-04-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_vehicleperson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehiclePerson',
            new_name='VehiclePassenger',
        ),
        migrations.AlterModelOptions(
            name='vehiclepassenger',
            options={'managed': True, 'ordering': ['vehicle', 'passenger'], 'verbose_name': 'Vehicle Passenger', 'verbose_name_plural': 'Vehicle Passenger'},
        ),
        migrations.RenameField(
            model_name='vehiclepassenger',
            old_name='person',
            new_name='passenger',
        ),
        migrations.RenameField(
            model_name='vehiclepassenger',
            old_name='vehicle_person_id',
            new_name='vehicle_passenger_id',
        ),
        migrations.AlterUniqueTogether(
            name='vehiclepassenger',
            unique_together={('vehicle', 'passenger')},
        ),
        migrations.AlterModelTable(
            name='vehiclepassenger',
            table='vehicle_passenger',
        ),
    ]
